// -*- coding: utf-8 -*-
// src/Base/Features/CustomFeature/Structures/CustomFeatureRebuildResult.cs
//*********************************************************************
//xCAD
//Copyright(C) 2024 Xarial Pty Limited
//Product URL: https://www.xcad.net
//License: https://xcad.xarial.com/license/
//*********************************************************************
// 说明：
// 定义宏特征OnRebuild回调的返回结果结构。
// 支持返回几何体结果（多个实体）或状态结果（成功/失败及错误消息）。
//*********************************************************************

using Xarial.XCad.Geometry;

namespace Xarial.XCad.Features.CustomFeature.Structures
{
    /// <summary>
    /// Rebuild result of the <see cref="IXCustomFeature"/>
    /// <see cref="IXCustomFeature"/> 的重建结果
    /// </summary>
    public class CustomFeatureRebuildResult
    {
        /// <summary>
        /// Creates rebuild result from bodies
        /// 根据几何体结果创建重建结果
        /// </summary>
        /// <param name="bodies">Bodies</param>
        /// <returns>Rebuild result</returns>
        public static CustomFeatureBodyRebuildResult FromBodies(params IXBody[] bodies)
            => new CustomFeatureBodyRebuildResult()
            {
                Bodies = bodies
            };

        /// <summary>
        /// Creates rebuild result from status
        /// 根据状态创建重建结果
        /// </summary>
        /// <param name="result">Result</param>
        /// <param name="errMsg">Error if failed or warning</param>
        /// <returns>Rebuild result</returns>
        public static CustomFeatureRebuildResult FromStatus(bool result, string errMsg = "")
            => new CustomFeatureRebuildResult()
            {
                Result = result,
                ErrorMessage = errMsg
            };

        /// <summary>
        /// Status result
        /// 状态结果
        /// </summary>
        public bool Result { get; set; }

        /// <summary>
        /// Error message
        /// 错误消息
        /// </summary>
        public string ErrorMessage { get; set; }
    }

    /// <summary>
    /// Bodies result of the <see cref="IXCustomFeature"/>
    /// <see cref="IXCustomFeature"/> 的几何体重建结果
    /// </summary>
    public class CustomFeatureBodyRebuildResult : CustomFeatureRebuildResult
    {
        /// <summary>
        /// Bodies generated by macro feature
        /// 宏特征生成的几何体
        /// </summary>
        public IXBody[] Bodies { get; set; }
    }
}